version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: "no"
  php:
    image: php:8-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
  shell:
    image: php:8-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/bash
  phpunit:
    image: php:8-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  # fpm:
  #   image: php:8-fpm
  #   restart: always
  #   volumes:
  #     - .:/app
  # nginx:
  #   image: nginx:1.17.8-alpine
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - .:/app
  #     - ./var/log/nginx:/var/log/nginx
  #     - .conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
